#!/home/joshgabriel92/miniconda3/envs/PyPI_MPInterfaces_2.0.2/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from mpinterfaces.mpint_cli import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
