language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - python-scipy
    - python-pip
install:
   - pip install numpy
   - pip install codecov
   - python setup.py develop
   - cp config.yaml mpinterfaces/config_mine.yaml
cache:
   - pip
script: 
   - nosetests mpinterfaces --with-coverage
   - codecov
branches:
  except:
    - gh-pages
    - development
    - bitbucket_dev
notifications:
  email:
    recipients:
      - joshgabriel92@ufl.edu
      - monahan.seve@gmail.com
      - richardghennig@gmail.com
    on_success: always
    on_failure: always
