# Configure these settings and then move this
# file to your home directory ('~/config.yaml').

NAME: My_first_mpint_project

Config:
 username: joshgabriel92 
 mp_api: your_materials_project_api_key
 normal_binary: /path/to/vasp/executable
 twod_binary: /path/to/2D/vasp/executable
 potentials: /path/to/POTCAR/files
 potentials_map: /path/to/potential_map
 submit_file: /path/to/submit_file_template

INCAR_general:
 ENCUT: 500
 AGGAC: 0.0
 GGA : Bo
 PARAM1 : 0.1833333333
 PARAM2 : 0.22
 ALGO:  F
 PREC : Accurate
 SIGMA : 0.1
 ISMEAR : 1
 EDIFF: 1.0e-06
 IBRION : 2
 ISIF : 3
 NSW : 60
 ISPIN : 2
 LCHARG : False
 LORBIT : 11
 LUSE_VDW : True
 LWAVE : False
 NPAR : 4

KPOINTS_general:
 Kpts_Grid: Gamma_Atom_Density
 Density: 1000

